### ISSUE TITLE
Navigating with arrow keys does not use selection for copy 

### ISSUE THREAD

**Issue by lentferj** [NilsKr/JD08PatchManager#2]
If you navigate the left window up and down with the arrow key, the grey box moves with the keys, but if you click ">>" it will only copy what has been selected with a mouse click.

**Comment by NilsKr** [comment]
Will attempt to fix this. Thanks.

**Comment by NilsKr** [comment]
Fixed in version 1.0.4

**Comment by lentferj** [comment]
I tried with the latest commits and the behaviour didn't change at all for me. I maybe have a look later myself, could be a platform thing, but I actually doubt that.

**Comment by NilsKr** [comment]
Which OS/version are you running on?
Could it be that the keycodes in the keyup event are OS specific?
Maybe you can uncomment  # print(e.keycode) in line 297 so we see which keys are being reported?

**Comment by lentferj** [comment]
I am on Debian 11.
So..
down -- 116
up -- 111
space -- 65

But that is really strange, such things should be platform independent in Python as it makes portability a horror.

**Comment by lentferj** [comment]
maybe better use e.keysym?

**Comment by lentferj** [comment]
I am preparing a patch that works for me and hopefully works platform independent

**Comment by NilsKr** [comment]
Sorry, I went in and made the changes myself, then committed them, then saw your comment and PR.
This is my first open source project, never had anyone else do a PR on here. I will improve with time.
Thanks!

**Comment by lentferj** [comment]
confirmed working with v1.0.5
