### ISSUE TITLE
Feature request: add short cut keys for ">>" and "<<" actions

### ISSUE THREAD

**Issue by lentferj** [NilsKr/JD08PatchManager#3]
When working on consolidating larger collections it would be nice if you could use keys on the computer keyboard for moving patches from left to right and vice versa.

Thanks for considering!

**Comment by NilsKr** [comment]
I'll have to find out how to do that :-) If it helps, double-clicking on the source item will also copy the patch over to the destination slot.

**Comment by NilsKr** [comment]
When the destination slot has been selected and the source list has the patch to be copied selected, pressing the space bar will copy that patch over. Available from version 1.0.4

**Comment by lentferj** [comment]
works with space key since v1.0.5
